compiler:
  solc:
    version: 0.6.0
    
dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

networks:
  sepolia:
    host: https://sepolia.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
    chainid: 11155111
